---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-endpoints
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/endpoints/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
