---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: influxdb
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/influxdb
      tag: 2.4.0-debian-11-r0
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false
    auth:
      enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: influxdb-config
    resources:
      requests:
        memory: 4096Mi
        cpu: 500m
      limits:
        memory: 8192Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
    user:
      username: "hassio"
      password: "hassio123"
