---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: hajimari
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/hostname: hajimari.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
