apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: unifi
  name: unifi-udp
  namespace: unifi
spec:
  loadBalancerIP: ${SVC_UNIFI_ADDR}
  ports:
    - name: stun-port
      port: 3478
      protocol: UDP
    - name: ap-discovery
      port: 10001
      protocol: UDP
  selector:
    app: unifi
  type: LoadBalancer
