---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-plugin
        namespace: flux-system
  install:
    createNamespace: true
  values:
