---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - system-upgrade-controller
  - traefik
  - jaeger
  - kube-prometheus-stack.yaml
  - kyverno.yaml
  - actions-runner-controller.yaml
