---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://halkeye.github.io/helm-charts/
      chart: fireflyiii
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: halkeye-charts
        namespace: flux-system
      interval: 5m
  values: 
    image:
      repository: fireflyiii/core
      tag: version-5.6.12
    persistence:
      data:
        enable: true
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - "firefly.${SECRET_DOMAIN}"
      tls:
        - hosts:
          - "firefly.${SECRET_DOMAIN}"