---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: firefly
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami/
      chart: postgresql
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values: 
    fullnameOverride: firefly-postgresql
    persistence:
      enabled: true
      size: 10Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 10s
        scrapeTimeout: 10s
