---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  # - coredns
  - descheduler
  # - node-feature-discovery
  - reflector
  # - intel-gpu-plugin
  - snapshot-controller/ks.yaml
