---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/loki
    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 60Gi
      storageClassName: 'local-path'
    serviceMonitor:
      enabled: true
    securityContext:
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    config:
      ingester:
        wal:
          enabled: true
          dir: /data/loki/wal
      table_manager:
        retention_deletes_enabled: true
        retention_period: 672h
    #Workaround for external-dns https://github.com/kubernetes-sigs/external-dns/issues/1257#issuecomment-628638415
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations: 
        external-dns.alpha.kubernetes.io/hostname: loki.${SECRET_DOMAIN}
        external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
      hosts:
        - host: loki.${SECRET_DOMAIN}