---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    hostNetwork: true
    probes:
      liveness:
        custom: true
        spec:
          httpGet:
            path: /manifest.json
            port: 8123
          initialDelaySeconds: 3
          periodSeconds: 3
    podAnnotations:
      backup.velero.io/backup-volumes: config
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.8.3
    env:
      TZ: "America/Denver"
    # envFrom:
    #   - secretRef:
    #       name: home-assistant
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: home
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
      backup:
        enabled: true
        existingClaim: home-assistant-backup-v1
        mountPath: /config/backups
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_bac559454b98ec1186ebacd044d80d13-if00-port0
    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.5.0
        # git:
        #   deployKeySecret: code-server
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        volumeMounts:
          - name: config
            mountPath: /config
    controller:
      enabled: true
      replicas: 2
    resources:
      requests:
        cpu: 35m
        memory: 3000Mi
      limits:
        memory: 8000Mi
