---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: flaresolverr
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    podLabels:
      setGateway: "true"
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      pullPolicy: IfNotPresent
      tag: v1.2.8

    env:
      TZ: "${TIMEZONE}"
