#Ansible import_playbook
# Inspiration: https://www.terasq.com/2019/03/building-kali-with-vagrant-ansible-p1/
- name: Install Dependencies
  hosts: all
  become: yes
  vars:
      packages:
      - python3-pip
      - virtualenv
      - python3-setuptools
      - tasksel
      - xclip
      - libcanberra-gtk-module
      - libcanberra-gtk3-module

  - name: Update repositories cache
    apt:
      update_cache: yes
      upgrade: full

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"

