---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: recyclarr
      version: 3.0.16
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "${TIMEZONE}"
      CRON_SCHEDULE: "@daily"
    service:
      main:
        enabled: true
        ports:
          main:
            enabled: true

    installContainers:
      initconfig:
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
          - name: config
            mountPath: /gordo/k8s/media-config
            storageClass: "nfs-client"
        command: ["recyclarr", "create-config"]
    persistence:
      config:
        enabled: true
        mountPath: /gordo/k8s/media-config
        storageClass: "nfs-client"
    podSecurityContext:
      runAsGroup: 0
      runAsUser: 0
    probes:
      liveness:
        enabled: true
      readiness:
        enabled: true
      startup:
        enabled: true
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    portal:
      enabled: false
