---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qbittorrent
  # - jackett
  # - prowlarr
  - flaresolverr
  - sonarr
  - recyclarr
  # - storage
  # - home-automation
  # - media
  # - system-upgrade
