tunnel: 'disabled'
enableIPv4Masquerade: false
endpointRoutes:
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false
containerRuntime:
  integration: containerd
hubble:
  enabled: true
  serviceMonitor:
    enabled: false
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    port: 9092
    serviceMonitor:
      enabled: false
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
prometheus:
  enabled: true
  port: 9091
  serviceMonitor:
    enabled: false
