---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1stlk3hjmzwps9dg0qjaqfdhwzvxj6vd2d3vqvkx7re5vdn4uaqvq6a3zxa
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1stlk3hjmzwps9dg0qjaqfdhwzvxj6vd2d3vqvkx7re5vdn4uaqvq6a3zxa
