---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1nmn3vnheehawum3h7fn8cygx24fwvtlh7wqepvxjf6ku4m95hv5qqz3ae2
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1nmn3vnheehawum3h7fn8cygx24fwvtlh7wqepvxjf6ku4m95hv5qqz3ae2
