kind: ENC[AES256_GCM,data:NRt6cTxM,iv:pc1hNoBBZ5/zKYf4Ni9Cv3OnuEdOpuyy5nVyLgArwNg=,tag:/msyiP3GGBhdaabnaNy8Lw==,type:str]
ansible_user: ENC[AES256_GCM,data:1EPaQ+A=,iv:1by07WkBYEs/CfIVk+0ZB9DPFcs7BFDX+br2gmG9OiI=,tag:dVf38rDoSFl4pvTx1fRMuw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:csSAmIkCh1U=,iv:MUll5aHeVmbRVJc6gz5PojIc0+iBuTxIAS4u3yJ/1kw=,tag:x0NFoELFtqS35MB8ScY5BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QzZhSmIwaDNld2dvZkJs
            RUNlTmRweVlpMzBVa3lxWlhWZVBWakhaZnhNCk02MDRORk9TaCs0RGtPUUtyOFNK
            Y004b1pYOFN1THI0QTUvNDA0TUl1Y1UKLS0tIEZwT1RQYkRzb0EzY2dBcVNtTGRs
            TmNhQlo1aUpzTUVQcGZiTkx4dU1DelUKGpy7ssF/7MFSxzJ+1txx5Em7hJYPEgKF
            N1Ug6tizsmNjsjIvadEX3wjX29OhehdMc7F6E79NxE4mi3LDUShUVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-24T21:13:04Z"
    mac: ENC[AES256_GCM,data:LCfbMfeGHO0Pj7fIUIobalL/2RyHBCeIg/wotX7ykEbNquubzBY8jx8lNtUafZ1jGGNMUJ717YsRnh/yZIb6hDc0P3WfVkfBSvJRSyCPuZdPkXpvT1gRIyhI3zUzojXSZr1Hd5FJu+kT0aNKOsuRN/4cvpesS20BrKr4WP4FSrE=,iv:/pLEHuzVYAIB3bwHRLazUCCh9B6748ouyb5hicT8dZQ=,tag:txR9lOTVn1f0NvUV+KcbdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
