kind: ENC[AES256_GCM,data:hkKCKppN,iv:1zcHxYF1e5QajaUXOjfRqY2iQaBFCBWsPTBeaK/giCk=,tag:+PkLqX9iLqx/0DV16FqUCA==,type:str]
ansible_user: ENC[AES256_GCM,data:7/bSiMg=,iv:BDZ0GgQMcEW7PzIjNG2q7getHM+uHfDC/ruGNU8Schw=,tag:wDUpiV25sUmQm4b4D8HS3g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cqiVLXejN1U=,iv:xW//KIneuPdPavW0l2X5ChCJ1MY39fyDvsty/9FVKJg=,tag:BdcbcPot0zcImiw8gA3k3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QXZ2WXFnUkx3WFF1bU5n
            elZ5MmllLzhYbzl4VlRMeVJ1VDBhTWtuajN3Ck0vdDllazlLUENycTJUY0liNzdZ
            amNSWmQ4ZjZYNUR4WHJQcHRBOG5nZUUKLS0tIE9LeWpkNzBLSGR2MWZLMUV5azlV
            WFgrMnBkZTNoU2t4eXhsc1ZNVGJFRzAKP+JVktJ3Ke0zxmALBbFhsVALIX67LVYL
            JXGNW93/qiuryQdTxpa/mx/or2ux49MOtinY4z26UPOSBikEdNVsvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T04:46:10Z"
    mac: ENC[AES256_GCM,data:7d8gDT9uUGnpzIcwF5kFhNfQZ3mj8vUZVcYNEVY7cOHOsM5jipqL3EbEIDYFBlEwfqsrhhzVvCVbtVmpfNFPhZmdTffu1h2BhlBrFTWef4TWEAog7WlG4/10CKnoY9Lr9TTtwfVZUmPR9sDeE/FTMF1lMBhWpBO13D8JjX/a5Vw=,iv:PXIIAhD1Atf9gClpqnCD2EsfhUHs+LgPqq4ppoFrt3Q=,tag:G9QiDhIFArAI+AjdYvstfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
