---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: birb-nest-cluster
  namespace: flux-system
spec:
  interval: 2h
  url: https://askalice.github.io/birb-nest-cluster/kubernetes/charts/
  timeout: 3m
