---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs-nfs
  namespace: flux-system
spec:
  interval: 15m
  url: https://openebs.github.io/dynamic-nfs-provisioner
  timeout: 3m
