---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: networking
subsets:
  - addresses:
      - ip: 172.16.0.222
    ports:
      - name: nfs-tcp
        port: 2049
        protocol: TCP
      - name: nfs-tcp2
        port: 111
        protocol: TCP
        protocol: TCP
      - name: proxmox
        port: 8006
        protocol: TCP
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-provisioner
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.16.0.222
  share: /gordo/k3s
  subDir: "$${.pvc.metadata.namespace}-$${.pvc.metadata.name}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
