---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: monitoring
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: 7.16.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1

    volumeClaimTemplate:
      storageClassName: nfs-client
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: 1Gi

    extraEnvs:
      - name: "ELASTICSEARCH_USERNAME"
        value: ${ELASTIC_USERNAME}
      - name: "ELASTICSEARCH_PASSWORD"
        value: ${ELASTIC_PASSWORD}

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        memory: 1024Mi
        cpu: 500m
      limits:
        memory: 8192Mi
    logstashConfig:
      logstash.yml: |
        http.host: 0.0.0.0
        xpack.monitoring.enabled: true
        xpack.monitoring.elasticsearch.username: '${ELASTICSEARCH_USERNAME}'
        xpack.monitoring.elasticsearch.password: '${ELASTICSEARCH_PASSWORD}'
        xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch-master:9200"]
        xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/elastic-certificate.crt

    logstashPipeline:
      logstash.conf: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => "http://elasticsearch-master.logging.svc.cluster.local:9200"
            manage_template => false
            index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
            document_type => "%{[@metadata][type]}"
          }
        }

    service:
      type: ClusterIP
      ports:
        - name: beats
          port: 5044
          protocol: TCP
          targetPort: 5044
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: http-test
          port: 9600
          targetPort: 9600
          protocol: TCP
        - name: gelf-tcp
          port: 12201
          targetPort: 12201
          protocol: TCP
        - name: syslog-tcp
          port: 1514
          targetPort: 1514
          protocol: TCP

    persistence:
      config:
        enabled: true
        existingClaim: logstash-config
    volumeClaimTemplates:
      - metadata:
          name: logstash-config
        spec:
          accessModes:
            - ReadWriteMany
          storageClassName: "nfs-client"
          resources:
            requests:
              storage: 200G
    extraVolumes:
      - name: logstash-config
        persistentVolumeClaim:
          claimName: logstash-config
      - name: logstash-certs
        persistentVolumeClaim:
          claimName: elasticsearch-certs
    extraVolumeMounts:
      - name: logstash-certs
        mountPath: /usr/share/logstash/config/certs
        readOnly: true
      - name: logstash-config
        mountPath: /usr/share/logstash/config
