---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: redpanda-operator
      version: 6.24.1
      sourceRef:
        kind: HelmRepository
        name: redpanda-charts
        namespace: flux-system
      interval: 5m
  values:
    monitoring:
      enabled: true
    
    
  