---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.vectorized.io
      chart: redpanda-operator
      version: 21.11.11
      sourceRef:
        kind: HelmRepository
        name: redpanda-charts
        namespace: flux-system
      interval: 5m
  values:
    monitoring:
      enabled: false
    
    
  
