---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-tobs
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/prom-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tobs-timescale
      namespace: monitoring
  interval: 30m
  retryInterval: 2m
  timeout: 1m
