apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NTs2xp30OJXrHf1TVm39GK4T4nzHXT4qwCwAlL46hEfSRj27htc3hw==,iv:RNDoqboldxTyyUqDzjQ4zynrY37cOH8nFKYzFUsTxhk=,tag:eN6CT7+QErNdlsImGopUhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOVRPL1Q0S3FKQjc4TjF0
            bFZCUVFDWEJrV0hub3lGcFlmTHplUGhXV1JZCjBLUmdsRFdUcTVNUlNyeWZZTENz
            U2hXYXVnMWJXWHJLTFhIZWdwU29iUFUKLS0tIDFXeXJRNW5tYmJyUnhaMzZXNDVZ
            S2luNnhoUmprVDJTQnJrdW5OOGFUYU0KP4n4tDFinserHEDgiFVF/eu2McPNkJD1
            PDz9jqoNqJGXYX1ASJs8bNpi3mVFBPZD5Oen+fLTixGzTmi45kQVxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-29T04:46:10Z"
    mac: ENC[AES256_GCM,data:HrKvUFPuVEutFJ4vopA0wHzMbIXYbXhx6LU2StELxL2MQS/47fSw28Dm1t4mmZPtgb/MiynXmA67gSbDqCsysuQcdxDcN7oWLwUOvE/UYzqOBQ+MYFIFiV8T6UA983j13bEjzUWSzZhvImXL7omHyqy9hdRmP+CkwRbA8p3VMT0=,iv:qKNyZXfr61ftCVRvnb2GsWn7ehqFo/FPTrM8Q1JJxrA=,tag:gA0JQfOP7wmwzim1b+N8RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
