---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: database
spec:
  releaseName: influxdb
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.10.7
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  upgrade:
    force: true
    remediation:
      retries: 3
      strategy: uninstall
  values:
    image:
      repository: "influxdb"
      tag: "2.1.1"
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 50Gi
      #existingClaim: influxdb-pvc
    resources:
      requests:
        memory: 1500Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    config:
      opentsdb:
        enabled: true
      graphite:
        enabled: false
