---
kubernetes:
  children:
    master:
      hosts:
        k3s-m0:
          ansible_host: 172.16.7.1
        k3s-m1:
          ansible_host: 172.16.7.2
    worker:
      hosts:
        k3s-2-jetson:
          ansible_host: 172.16.7.3
