---
kubernetes:
  children:
    master:
      hosts:
        k3s-5:
          ansible_host: 172.16.7.5
        k3s-4:
          ansible_host: 172.16.7.4
        k3s-1:
          ansible_host: 172.16.7.1
    worker:
      hosts:
        k3s-0:
          ansible_host: 172.16.7.0
        k3s-2-pi:
          ansible_host: 172.16.7.2
        k3s-3-jetson:
          ansible_host: 172.16.7.3
