---
kubernetes:
  children:
    master:
      hosts:
        k3s-m0:
          ansible_host: 172.16.7.0
        k3s-m1:
          ansible_host: 172.16.7.1
        k3s-m4:
          ansible_host: 172.16.7.4
    worker:
      hosts:
        k3s-2-pi:
          ansible_host: 172.16.7.2
        k3s-3-jetson:
          ansible_host: 172.16.7.3
