---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: qbittorrent-backup
  namespace: media
  labels:
    setGateway: false
spec:
  repository:
    name: b2-repo
  schedule: "15 02 * * *"
  target:
    alias: qbittorrent
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: qbittorrent
    volumeMounts:
      - name: config
        mountPath: /gordo/k8s/media-config
    paths:
      - /config
    exclude:
      - /config/lost+found
  retentionPolicy:
    name: "keep-last-7"
    keepLast: 7
    prune: true
