hnt_monitor:
  container_name: hnt_monitor
  image: hnt_monitor:latest
  build:
    dockerfile: ./build/docker/Dockerfile
    context: .
  environment:
    DO_NOT_REMOVE: "setup"
    HNT_HOTSPOT_MONITOR: "true"
    HNT_HOTSPOT_ADDRESSES: "<myminersaddress> " # Update your miner address on this line before launching the stack
    HNT_PROMETHEUS_PG_HOST: "http://prometheus_pushgateway:9091"
    HNT_DEBUG: "true"
  networks:
    hnt_monitor:
      ipv4_address: 10.30.0.05
  depends_on:
    - prometheus_pushgateway
