# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1LOgn9dK,iv:wnITYnDyCc6X0ExlTIfinX16V7wQt4J8N6kBHPUfNgo=,tag:DHITSSEDx8ppBJtsKMw1uA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:eC3lP6OFI6/Oj93gWi7iaFVKKIE5qXzZ,iv:j5El3b4E5yiRWn1qFymHudyrJduvh0w717Wil6PXZ0o=,tag:3nMNua4Hj54FCr1QpJK+3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uj0p9g9vje72g527usq2cyvmq2vatxwfp5suty94zsjvz6nxsppqk0cf9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUXkxcTZuTXhySUp2MFg2
            dWY2MDVSNXhxWjJ2ZlRCY1RvdXZYeVlQSW00ClZidTVOVXZmY0NuUVVwK2hLKzdv
            d08wOW1DQ2FSZFdXY0xsMkZOUVB3TEUKLS0tIHVGUnpLbThITFdBK09TMjlxOGhO
            cjJ6eDdoYjQwSk43ZU9wa1pUbUh4RUUKquezZ0/pVP03txxPztKflaOmTV6AAZum
            CnFk9+FOMObDil8XrWXKUgsEQyw7kCnH7WhO4tVh2jlWOgAlMYucOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-16T11:23:26Z"
    mac: ENC[AES256_GCM,data:nP5UzdpnNw7/89EBZ6khn2g9vwUjQKbNyeae2hscD9ey22QajAVlbKI2NtgqFfxd2WH6Lmecr2NIDWie9oMgC9KcJfjFD8rysPRpwfndiiEQuuW818tQ/G/OY1QPRg3rTMqROah8c4lJOl5s1hBDrK6mRL+2331tOW6r6eTr3hk=,iv:G+4bsAjWsl4k6BivcWihEFpYNAlunVxv9MR81L1wuwg=,tag:r/hp5Xj+GgbiX33QjmHk/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
