---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 172.16.0.23-172.16.0.33
  METALLB_K8S_GATEWAY_ADDR: 172.16.0.23
  METALLB_TRAEFIK_ADDR: 172.16.0.24
