---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: starboard-operator-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/aquasecurity/starboard.git
  ref:
    # renovate: registryUrl=https://https://github.com/aquasecurity/starboard
    tag: v0.15.4
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/deploy/crd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: starboard-operator-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: starboard-operator-crd-source
