---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prom-stack
  - grafana
  - loki/ks.yaml
  - elasticsearch
  # - logstash
  # - filebeat
  # - kibana
  # - tempo
  # - influxdb
