---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - metrics-server
  - node-problem-detector
  - prom-stack/ks.yaml # tobs
  - alert-manager
  - grafana
  - speedtest-exporter
  - vpa/ks.yaml
  - goldilocks/ks.yaml
  - loki/ks.yaml
