---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  metadataPool:
    replicated:
      size: 1
  dataPools:
    - replicated:
        size: 1
  preserveFilesystemOnDelete: false
  metadataServer:
    activeCount: 1
    activeStandby: true
