# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:H09vj+cnGEFxHm0o,iv:5IibJyQEPjdGcAF03bvawuXwSMsmRXFwFzWw6YHoUpg=,tag:bRNzv8L8igiQBytb0N/qTQ==,type:str]
    SECRET_GRAFANA_ADMIN: ENC[AES256_GCM,data:LJPCXec=,iv:BxQZ6MlxQuFTrmFpm8pghdaVjFHavqkVcFNUW9o/neQ=,tag:F5Kx0V0gZP+8Jhbx44+WdQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:zGix5LcP+ZU=,iv:PPkVWlaZs5DakUHNCwJ6UKloXOKkk3g7k8zzN71DqWI=,tag:FcQDBk67nEjWBzdN5PiW2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZzdQNVFHVnZYNG5vVS9k
            YkhyZ0VQR3lzSVZKczhIZWVjTkdrWjI0dDFnCkcwaDBkK0VOSU1RVDZwcDJNSUQz
            bmh5L0h3b3dBNjZ6YlA1WjVHUDlrQzgKLS0tIGhFUEJ4bUF0N0ZTMXhPTmpvaWhh
            bXB4VUVpd2ZIUjk0cDNuTTA2K0NabnMKIw+zdaXslGnz25BfT7FSSOHQMhXy2Kzw
            rzC3TP9zsciKVtlapqk0egiZD3tEMCmqO+LkHRTVVDa0mtAOsDTvZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-26T00:58:24Z"
    mac: ENC[AES256_GCM,data:0rgyO63af7QdUosFVswP7EenDbMEKBBLJ8156IQrGhqqI0vqiSg4Ex/5Xml59MKZB5SNJAmpqOLMfQApp8HbycxX8oxbZg9nZelSBXD4nFLz7x8uerEr2rxX5CzPH+Y0m234JPY6HZsEZScVzrHq8LmjoLYuGdZp16nKvyr+pSg=,iv:v5WQPthxM/Qefq3sOeIYYR3j8ePowZFT+/LyJZlHlgk=,tag:QjUhJePVi9tXYoBG9n0kDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
