# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:H09vj+cnGEFxHm0o,iv:5IibJyQEPjdGcAF03bvawuXwSMsmRXFwFzWw6YHoUpg=,tag:bRNzv8L8igiQBytb0N/qTQ==,type:str]
    SECRET_GRAFANA_ADMIN: ENC[AES256_GCM,data:LJPCXec=,iv:BxQZ6MlxQuFTrmFpm8pghdaVjFHavqkVcFNUW9o/neQ=,tag:F5Kx0V0gZP+8Jhbx44+WdQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:5CAfCVjQixP1,iv:mr+mJkqdXfUOZVfR9KdqW46JQH7b/Xy+eaIyAL73kkM=,tag:irUb99AHySa/xiRRl2bEDg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:x58xLkdHRewIVJ6RDTXM301wmq0=,iv:4Fq9hS6O/NwEWZu2riSLCnRwA7uN6ubNEQ0bqi5xBPU=,tag:U3+pv0S5tHlbxN9mzjIf2w==,type:str]
    SECRET_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:v0YOuYBjz/vwT5VZ3RLD26OLyqmpk1FdZkH8yxdC2BM=,iv:7fte90mQyAbn191PAkPXLpDZUOLNO4xkcxWGUOBnvKw=,tag:5ZnWhykMVMtpLAyPTl5biw==,type:str]
    SECRET_CLOUDFLARE_API: ENC[AES256_GCM,data:doXVuTUU4kgYOqB4CQjr7h5tbMF4hAM+ufdg8ShTLNmYBLGfAbSGUQ==,iv:6nYCrBtSG/fOOfbnhQ6RMkc7wA20LCsVJJzykTx+owA=,tag:DBgIHEGJb9qE8x22aTT01A==,type:str]
    SECRET_LOKI_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:ZZZry6DF1mU=,iv:fAKbD95IlRMOeqcxRTJ+uA5ImMI9iPPvJR5H8mLyycM=,tag:uqHWG+hXjjl4vt454wWXEg==,type:str]
    SECRET_LOKI_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:xCcxr3RQ9PTmREWFTWY=,iv:FMoG5CV6/aMIFtM3W/btPvAOT5vAeX3/SlEoRL6YJxg=,tag:3H7zmeSrYt4TVJ9Ohptyhw==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_USERNAME: ENC[AES256_GCM,data:XIoN2FqQe+s=,iv:fAPbDo9hxEBuyBIJ+idGQacod7rMIZmzApW3Ih5GuSg=,tag:3DdT+rkhmpFOYFg53zXoqA==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_PASSWORD: ENC[AES256_GCM,data:dxt5DJJ6JhjUudZesSk=,iv:GPeWTkLi+53aFX7dq+/o0VJwvTC9Csnzd/oH5u/4iUc=,tag:PC4lG7YZa57sLX5gcxu94w==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_HASH: ENC[AES256_GCM,data:GT00UzFfpP9fxCYerzUFyoj3r5QQbs9YE1lG/ZoTQvnbmQgFW1yax2GQm05m8WlgzePdWjXzPYcCGJNJ8kdk1g==,iv:xON6/Ww4GEOglP0CGHbVR1+/HH5KjztwNMlrI28lYQ8=,tag:EPiggEndak+0Uye3i9QfwQ==,type:str]
    SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:S699i0HU2FL0UQ==,iv:4NBbXf00+M0iJxVsU1y0ouZIXKVH2pZm4J4kAa6LM7U=,tag:lAAgixZpSSJNcVHdB4w9WA==,type:str]
    SECRET_FIREFLY_PASSWORD: ENC[AES256_GCM,data:n+enzkKKpJaWdEqrIeo=,iv:uztKFwkgp59Ol12YNMl2X8WQAk2RxewkjR48K98DhkA=,tag:JoQ6lumqImb+AnXmFyrt9Q==,type:str]
    #ENC[AES256_GCM,data:z67NbVm2kg==,iv:COdMgEPYbTEnE9u02VSoOQrFI2CegKwytfUZ/ttt0Tk=,tag:EIpUepylPJJyQK/2jBbmtw==,type:comment]
    SECRET_FIREFLY_APPKEY: ENC[AES256_GCM,data:nS/q7K4oXFNSPmO2pY+dNElIncmHM5BxBpNFjXIHsAQ=,iv:LkPFHSBaRGsPb94e6uflmVS7JzOEsNTXbNOrEImj+pI=,tag:SbW58yek/ybMOgoSnSaU7A==,type:str]
    SECRET_PAPERLESS_USERNAME: ENC[AES256_GCM,data:ECoKM9gXqbA=,iv:edmrP9cD061wuO5NruY+6NLNf4lJLwFiUe0QRycLSVw=,tag:aFhQOsPN6sbrJIolfkIaWQ==,type:str]
    SECRET_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:MzmhngmlbjsFzFg1TY8=,iv:XqqjXmv1SwlCZKuqpBZaA+0NNRdE7h7gbUVgMvfAnXk=,tag:YDbC97Pc3JRnlsjCJgzx2A==,type:str]
    #ENC[AES256_GCM,data:HNw9Fg3eg2k=,iv:6OMSoWWpjHEYutk7xQvEuk9gNJneiR+t3ALlDDe2kKg=,tag:jNQYAeZNJF8O7dOTD2bIDA==,type:comment]
    SVC_NGINX_ADDR: ENC[AES256_GCM,data:mcMR8nwxk5xkSg==,iv:dBluV8+g/Bg8kGUNGrDGwrQlJ+ZFIyIsDqwmfHa1GVo=,tag:9GMgaONutpa9upOs3hXddA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZzdQNVFHVnZYNG5vVS9k
            YkhyZ0VQR3lzSVZKczhIZWVjTkdrWjI0dDFnCkcwaDBkK0VOSU1RVDZwcDJNSUQz
            bmh5L0h3b3dBNjZ6YlA1WjVHUDlrQzgKLS0tIGhFUEJ4bUF0N0ZTMXhPTmpvaWhh
            bXB4VUVpd2ZIUjk0cDNuTTA2K0NabnMKIw+zdaXslGnz25BfT7FSSOHQMhXy2Kzw
            rzC3TP9zsciKVtlapqk0egiZD3tEMCmqO+LkHRTVVDa0mtAOsDTvZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T20:56:07Z"
    mac: ENC[AES256_GCM,data:RSjmmBS9f2yozGq5KtoUdyAFptwk4VCq1HVf2U3mSGSB2wTQNdG6YKscMK3SiWe3j8QogPWq1mcL/a7Ha2Jnm9akTBYFqujmmf9wfB34rdFJ3ujeUTi0O/YYO2bZJxfcmihP5A5IjQ8zTFaelxCJpfpVBbp1Pwm4dj6wX5GBsHE=,iv:s96hY3Yz59ob5x2ruYs5xKV6N/28IwKrNJSP2jlJo3g=,tag:sAV+7s8+SLbip47k8VaZ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
