# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:H09vj+cnGEFxHm0o,iv:5IibJyQEPjdGcAF03bvawuXwSMsmRXFwFzWw6YHoUpg=,tag:bRNzv8L8igiQBytb0N/qTQ==,type:str]
    SECRET_GRAFANA_ADMIN: ENC[AES256_GCM,data:LJPCXec=,iv:BxQZ6MlxQuFTrmFpm8pghdaVjFHavqkVcFNUW9o/neQ=,tag:F5Kx0V0gZP+8Jhbx44+WdQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:zGix5LcP+ZU=,iv:PPkVWlaZs5DakUHNCwJ6UKloXOKkk3g7k8zzN71DqWI=,tag:FcQDBk67nEjWBzdN5PiW2A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:x58xLkdHRewIVJ6RDTXM301wmq0=,iv:4Fq9hS6O/NwEWZu2riSLCnRwA7uN6ubNEQ0bqi5xBPU=,tag:U3+pv0S5tHlbxN9mzjIf2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZzdQNVFHVnZYNG5vVS9k
            YkhyZ0VQR3lzSVZKczhIZWVjTkdrWjI0dDFnCkcwaDBkK0VOSU1RVDZwcDJNSUQz
            bmh5L0h3b3dBNjZ6YlA1WjVHUDlrQzgKLS0tIGhFUEJ4bUF0N0ZTMXhPTmpvaWhh
            bXB4VUVpd2ZIUjk0cDNuTTA2K0NabnMKIw+zdaXslGnz25BfT7FSSOHQMhXy2Kzw
            rzC3TP9zsciKVtlapqk0egiZD3tEMCmqO+LkHRTVVDa0mtAOsDTvZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T01:19:46Z"
    mac: ENC[AES256_GCM,data:K9E8KAw3jGBVVsbQG2XX+BkCsjoV/LkoHk7EthTthgrRdRpBkaCA5WcvurYx5HTe0fTZ8C87qBxklwimAfuOq+ryUVSrQD33Gm+Iy5v99U7pBFac0PvZZ8gt1wcoMOLOXandz191S4mSPZAdL/yBTe91png+MuZTR9rGdYYBvfQ=,iv:469oGHg48RMncOY/AyzeOiTB40bRQ+oe5db8nFZYxxo=,tag:f+jTE0j4wfA6ibzZZMxVEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
