# secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: firefly-secrets
    namespace: firefly
type: Opaque
stringData:
    db_password: ENC[AES256_GCM,data:g72NuilNKoy8Oxm6gRHv2tKnv5C0GOnKQL8xZGIN9OI=,iv:4sEAFRIBwebk66zVcjRb9wp7Zv7mn0F9SeKVnkM09t0=,tag:bhJDIHsy2WHL11WgEfRv1Q==,type:str]
    app_key: ENC[AES256_GCM,data:b/uT08b2os78WXxsrQVvJdPcloLEI7faqe43VMb9GEE=,iv:Ic29l6GFXLiC/rE/NMfhGCxDVQ5stKs1odZZrVQzXKk=,tag:NMLufPKWOCi/9HsVIGfsXg==,type:str]
    access_token: ENC[AES256_GCM,data:OquOhLXBdkoZG1TykK03AP+xy5mSKLUUdsIiebt4s+0=,iv:B8a1rIG3NqghX5sgwAZQZAZid5h1bC71NaZ01ElTEEo=,tag:svI9MKnDoTlo1tLm4SajBA==,type:str]
    static_cron_token: ENC[AES256_GCM,data:4A949dazLGSKda9Wm/5nhUhNPRejizyjggw5L1ZmFL0=,iv:57rhsC6l4nvypM9/A8G1dY+GaGi8mKf39tfw9669SUU=,tag:6WkpkMmFbftlB45Un/eRAQ==,type:str]
    nordigen_id: ENC[AES256_GCM,data:a47r1kFRkOxL2RZWvIA/wdW94P5MvltUCByxk5DGmUc9f5Gs,iv:ob3wMGc6dXTKGBkHe3SwjyNeDM4Lc5t0vi9XWPLaHfQ=,tag:yAbTlgpqItT+LBhflm6QOg==,type:str]
    nordigen_secret: ENC[AES256_GCM,data:E+shGeTRRgJbMlb1Vtds4CJCbOd6M30f3i6WB9+9yYy+spoK2ZlJxeL1w9YeTgVUXy+K/rT8dTAxaDpp0T6qyIBZduClhLF3XOLaH1E7rBU+Z5VdQWaTs7OaJ4kjzIn+E9OiM/ytYE+sYDgkBckk0ahG9op0ZWoCW12S1evNrqg=,iv:78bH34NUoJSbWXSans3NCpD74siUgyY3GzpQW8t54Xs=,tag:f+9NRawac2Dc3+dS60J0vA==,type:str]
    personal_access_token: ENC[AES256_GCM,data:tfhLWg3lPf9KBaXh7wliVCbwbnYMMpNphhtMVLQbKQscWIegDnuLSXW6fxxGG+PYiRWYPaXMCL8dcKpyCEACXkwu4IsRRUGNLMk0TksFa7kNhFwmtXMvCiBqDCv9a9WUkSHd3EyOlWC5QwfTyOGSgy5ZdxeWFaY/mJnOz0pagR9+RZrFFKvHFp0H010w+6eWOL337iEMV7qSLdJv4Xy8gfusGYaqtTEjDSU/9rEphwfz0s33tGImrMI2itPjypjxFV0JQcGEX7kZhLoULhA4ivWvKryuIEbJvERnSoDCI3gmefd0n+6X17qGI3YdgDWe1qsSnJK+uQ9MV5cfmYDDOImdCnriQioS+F+DqApVoegymc9qbsQ/Q/XM7OuZm/1rjuLD/E61Z/pLyb7q3a4E3xe9o3ZfKOU9GE4MKhkgeGxGGZ8vC4WubogexZT7RzzleC8jhBcWJLd3Lsyr1GOmxWtzX9dtaRhwlrzthJZtQdyeiBHBIJG9huEQbnw8s4NX0doZOomAMmN1HloR46tEQPLT0JdTTloa5Am+yjo5on4nOH2xZUh/rP/s7i14fybPRtCFsqoGHY40RnzH1n4GMGtctAZmVcktBPhN0NEXcezYvGm2vZPrM74jXdsieDvyridDpQ7iVbpsEE/+iQ/PoZtohKAFzTZW/13kWlUCz9FEaKBLodmcbtKxRlTe9oRg90LxG4rRdiciM1d1HkIibjoN2fK5rQjGfnDXbe6GiRxLafhkJ1SQ2VpYH5USto+GAcQw/MEnpoTtHHTjx4MdZ24UGmgnVjIdw4oHvEI4o4JNm1o5fp/aeFYZeIfXcTkAal7WoFYlnKcgtM2VBHPBetF25MKBTWXy4W3O3sUl2BRQR4AouXB/xuh/gdAnb0gSb+OtjyiT71h/7U8Y5UkeNK8scfdJ3jR/eP1Z50WbhlFZM3dR0HJi3hRVTqY8ecxORIcHM81dBsvWmrtcPRwT5jjkkz+HVx9YEHAIjq2QE7CLqQhjirbk7qKdJWyDJDo2dSCz+wfOXvG2N6R+EHCyKfiVbTB2dzx6BpUgvkjUMNcivRCipANGsB7wLiZcyDZnOH2MpkvDK7c8nTssP5Yr4sOdEsUNSzUlqQKQ5ahSwXSLSaJRfvtwiG1DdTBn/kzfhezGxSWJ+bQMKY8iBF1xNbJcsh97+OlUzKbbMnFCyNvAmcpv6zLT85fyhJGdzj6r4YiKJhVkaBg+dUly1MoOauog7IpqUmk6npoHcsx/556rro8/gDkLCctNSq3sYB/dfJYY6TOvUJXsqAG3FJe9mjJ8UFs=,iv:aTLjxf57czZsoFXYu93RzdxOzpi2QKnfcoJ0K2vUqE0=,tag:fTDvqU52DDkiumldv6gXGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUTlDbUlQTEVXYWZ3RWg5
            eng3RmxGYlRoVE1QV2t4ekV0dldCUnZhZHdFCndjYnVJd0ozbml0eHQvWjRsdnJN
            am5RcHpiamRwWkc5b2xRdm8vQ1doY0EKLS0tIFpTTXBwUGU3ZUVYZmg2bVVBWDF0
            WkZHZkdKVlZhZ0ZEMzZVaFpTMzJwOFEKpvfBWRcZgXfMVebJp0oA0NGd8S+oGunf
            7FOfn2CFlZs79WuZi8aPcZRRzpKqjHGDhxZV/1j2tD7jZxHmn4HdeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T18:04:40Z"
    mac: ENC[AES256_GCM,data:mw1ZfL52T3DKP7ATeqnGGB9W6LnbRRirwa6KlcsSr7fM4QtkXCDTxweqPZgrw4yj19VUizszAa5cTHdtQoK0Iv8QxMmWUhJQcng4pgQ/9FjW2sdNWUEbXoTtICZhj6u2QZGhwvfj6aKXuTtLd3NyZBYxqMv9S9JzmRHAoGUkRCo=,iv:abmAyQJkNN/K8mVPqMeMUalSIfvPdlMMnsmmngl1xgU=,tag:uRsMmlrXoQteDY9gjt6xfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
