apiVersion: v1
kind: Secret
metadata:
    name: prometheus-basic-auth
    namespace: monitoring
data:
    users: ENC[AES256_GCM,data:EbFQ4DWo7IBAw6t10pWX3IOF1vrPo1eKhfLKwpSr8at1rNJCQQ4PzQDlnMN5bkYVFXpM5tWJnF1buqbTWPuscg==,iv:g+RPr4BoIqM9bM+JMOs6zOXBCuuqFnOA50CW++IlLlk=,tag:Kk9/ukWSOJJe/LV5xVcoEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TW9mL3pMRHJMQUpSVlVo
            aXdRUWFmcVFOOUR5RHB5c2hlTVZlSmtaSzJRCm5pK01NemNFMU56STRhTGIyRjJo
            VjBHN2xOWTlUb25LNjB3MmVONmt3MEkKLS0tIC9DODdqQ1RSZUtzb3pYY2FjbEpk
            VmU2SG5UYkczMytnQjdSTExkNW1iOUUKAA2/aCdGAbgslmLgX9zDc4lnx4ysNUFI
            6jTsOxziqQ8Bcf8PGKfCu/HUH87D5Fr6aGsag3FQbgT6XLGBm6Gu3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T18:26:09Z"
    mac: ENC[AES256_GCM,data:gn3DHd0VSmavYBR5RAVKgW8AluSmJEYa1TObt64zEMbAvDSrTTtvVqlu0gLI6HJTcGr12r60NIadR1Qi7upHuchjqCG6OFoujapCz6DgM9bJoI9lYpambc9DsofiHfxRBhj8qo+fLbKtc7T6OtdbIRENBBHAWEud6WuWXhFue0k=,iv:22aDaQdUan/INpD4i+bssk7gtTm39p5/RNFVk7H+1+s=,tag:tnNbJ2jrwHMdaQ+LFNLJlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
