---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/elasticsearch/operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: cluster
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: eck-operator
      namespace: search
  interval: 30m
  retryInterval: 1m
  timeout: 3m
