---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wg-access-server
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: wireguard
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: wg-access-server
        namespace: flux-system
      interval: 5m
  values:
