apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:/RBojt1mmOlNFqCQ6SUL4knu/wkGTjaQ50Cax6NxzQu2aukguAVD+g==,iv:FaUaZQHxLMt3z395RJUW37q1nxpQzCpP95TEoLLkRHQ=,tag:WhB44rGDGkWyVEavhV1ztg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwemVQeUxYZUVVTFpSY3Fw
            TFhUa0g3TWFQVEJpeHA4bmtIbTNidjJlRWd3CmxOKzBxN1FENHZyY1laeU9qZDI0
            YWZnNS9kL0x6NCtzRjVXSHNHOXdiODQKLS0tIEdVazcvZHFUZWNJN3I2VXVLd1lK
            M0t4ZklpR0ZVTGZhNG5aenBSVlhRUTgK8qK9x2WJFV/CtNMga0y1U79fjK1sMBEd
            ihidXK812rO22oUAsZFOhAMFHvRRdpIpuR+/gw0JUbEl8Go25pXOxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T18:07:01Z"
    mac: ENC[AES256_GCM,data:ZIrI8wneHcn0PVIE6G27CKFoESB8vZsbGUW4rE9z2T/sbRVEw1zVgLWXRtckkyWZX04d84HfR0+Gey3YpXdx3I0qdrUBIe7neqjYLnWUx/cKa6e1JhuocFtdOMMsFTT91zCoOJiKDqhk9iagA7kl9XJZIoSueHgt/sK19/n6ARQ=,iv:9aDsR2vSZZWcbVEuT08MxMF702jFYD5XfqAM+K6zqoU=,tag:fMprr3vmPhkHPfEl99Qztw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
