apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:DpPs6Zs9Pml2Y3/OD6ZmjyPmpDYbbM6TN8OjlKmKoEbpIUfrTw==,iv:WeTiO7pJCb81fzKadBmBbei7fLqC1zsl9Se2m0kyL0w=,tag:EEvsTQE6iV6NyCD8cFIl0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR0FrUmJldjVqbW9jdW1V
            ODVaeEVSbnp3a0JSNVUreEtXdEZacUdWUnpBCmxEcXJLV3ZjZUJHQVJZSk1xVXZW
            QkQyTWFKSkRXYkhFdzJpM2lyNEVlTVEKLS0tIEFuSmJaRHlYK0dYNG1ydHhNWjJN
            VHBHUU5ldG9hWDZ4cnhGZHJrRXh3Q0UK7woYMlh8/prwDo2Q5bLgziX+BaG1/aQU
            7VvPgVbjIDD6jkOc3vnT+85UvrCeHXs38fFOxaLxYuNj3NIXUdvEow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T00:51:47Z"
    mac: ENC[AES256_GCM,data:KzXqDRNPKLeWCGFkGaA9xeSY/mbr0EpzMTh6wC13nFh7UcGb08NSXohqNTkk1+5fSb4BF/FYmJ0ubsaVK6Hie3EWF3vAG8KurWG8WinRQqfUk+0JTJ1o2nq1L0qdjh4tpOCdzm4IGjrODDIDCvTPz0tAT5+kKvnr+F+7g6SdAU4=,iv:g48SFctK+ce4oqcpxOijPh3A98vevSTWuXxwDXKRkQA=,tag:uTJjtgf7ZeFHTDobmXRyvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
