kind: Secret
ansible_user: ENC[AES256_GCM,data:QZjsTk4=,iv:1+lizEg4RMnX/2pr7BK4qPdq9r3zkialsTlWf0FNlwE=,tag:i2IqGrP+eAXedeXqtJ51xQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kVENmi3xX/8=,iv:YRR/9tvTRlc9KqgQ58+dh4I4Y6SVXtsfXmjCoaYNmTg=,tag:paTEwIT4BqvXjU/YpNY9lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uj0p9g9vje72g527usq2cyvmq2vatxwfp5suty94zsjvz6nxsppqk0cf9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VnNDclFqZ1REeENrVnZV
            N0prM3p4MXVvc1hlMitQQjZVU0R1cnluY2l3ClJzWUZQZDAxaEVscFR4azV5RHRy
            Qk1Lelg1OWV2UFdMOFZ2ay9XMmdSRHcKLS0tIG11SkRiemJnWGxLbFhmZlEwcHV3
            YnRtaWVnKzd4bi84NnQzKytnSU9Xd28KVOZOmDIunZfB8kCbllzNysUyOA099tkl
            SseCwJ11zO2BmGE3wpuzMV/ftcJBTI43Qg02CGfDR52ej7WD6SmBOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T14:33:50Z"
    mac: ENC[AES256_GCM,data:EqGKub5SeUvYmdopfytnhV9F+KP3g/+qM3dGaFyVfPGB4BlAms2KxGCM5YSbofhsdcHHux76Njw11kejMuYx7GBFl+4zu+SojY5MCzLtb65sad8ZxIIpLDUfpsZ5FKqtBYoyuhSNFyZwSncx7Ler925zoZVA4YX5m89iQuXsp4Y=,iv:CAHn+eOgYZBFp+Lx9CQrHaJbaZ7ju1cm0+k6IFKQrc4=,tag:TuDEkuHkHbff3AymkfbK7w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
