---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    podLabels:
      setGateway: "true"
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1802
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
