---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-config
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "kibana"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-certs
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "elasticsearch-certs"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
