---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.0.200-10.0.0.250
  SVC_TRAEFIK_ADDR: 10.0.0.200
  SVC_UNIFI_ADDR: 10.0.0.210
  SVC_UNIFI_CODESERVER_ADDR: 10.0.0.211
  WONDERFUL_CINNABAR_BEE_ADDR: 100.72.246.45
