apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: redpanda-operator
    app.kubernetes.io/name: redpanda-operator
  name: redpanda-operator-metrics-monitor
  namespace: dev
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - dev
  selector:
    matchLabels:
      app.kubernetes.io/instance: redpanda-operator
      app.kubernetes.io/name: redpanda-operator