---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-config
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "elasticsearch"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: "nfs-client"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-certs
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "elasticsearch-certs"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
