# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: es-developer
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hZzPZsE=,iv:h2P3Q0KvvBtkol8LAaM0EAHHetr8aQfZhbnwzgHHg2c=,tag:6gl7tVfTV3MGyDtGD+FGsg==,type:str]
    password: ENC[AES256_GCM,data:Q6XPkYI=,iv:L6F21xevo0Mauht9b/qtKlBNznvtdRPmwEL8QB8KF60=,tag:V9bk3hOxZO3wWs3t8y9olA==,type:str]
    roles: ENC[AES256_GCM,data:0rIgniLv835XU6JZmQ==,iv:iQp5Xy+ct6MlKLyHupZmjW/PxQKqJv2s1lJBxWwEYH4=,tag:9ppBIQzoHR2XGqJUoq2PxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ang2RVNWeG0vNHdPbjF4
            WkVuaG5oRHBaOGZkNDZkSldUeWVtbkMrSndZCk1hZCtlZ2tvWSs0M0grR3Y5Qmgy
            bWFlSGRONGNRaDFnNEppQWtneGp4cW8KLS0tIEkxYVNsUDhwZWVHTTUyTnpXUkpT
            VlVQUll1WVZNYk9kWE0wMG5VVmR4RnMKgEmxdd6rTnftyVlMMSNrsV/plRE+ppGa
            teMESrrgWge/IBO0TM+VvzWC3Xf7y79FiNXVynKKtVAjwfLBcvmF2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T18:07:01Z"
    mac: ENC[AES256_GCM,data:2tUMYeutJh0MuxqtzKEBgmWJNozOJodhwfb6OGV4eauL9mOXseHj9SpKUSWkPRiJNDcp20OlPVi/njOqSeVOvUZvujkX7zRhYhA2vHfbUevgGZwSN56rFgz6EwOOoDqZL4zt0CBcRoNiMafB2OsUWvX5PW1bvyFT76nX/ncnNOA=,iv:X1H2TO1vZZcveZKNSYdTjuL+qQZBr0pPKtud+4s748I=,tag:AcRKpCrAdQ32cYmp8NmIqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: es-elastic
    namespace: monitoring
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PMg/E2s=,iv:3BDVzW/UESrmoTrKrsoIQMs+9cw7JE3zfZHHHixkSoY=,tag:Vf2FQBL4lvPvlkCWpPTSHg==,type:str]
    password: ENC[AES256_GCM,data:vY3TTWo=,iv:aGT4Ufo601gMOgGnWYuP9qOh6HIfYyDCWBBRcdsHReU=,tag:a9lssDaYK2XyKQ+XfYQFgQ==,type:str]
    roles: ENC[AES256_GCM,data:+V+5Tdsn5CduleUJ8w==,iv:BlvEDYef9aNCypZL20dpa9inrVwZOog/yLYvs/6mUy0=,tag:OHG/Fq+BWD2UGu7y3cUDJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ang2RVNWeG0vNHdPbjF4
            WkVuaG5oRHBaOGZkNDZkSldUeWVtbkMrSndZCk1hZCtlZ2tvWSs0M0grR3Y5Qmgy
            bWFlSGRONGNRaDFnNEppQWtneGp4cW8KLS0tIEkxYVNsUDhwZWVHTTUyTnpXUkpT
            VlVQUll1WVZNYk9kWE0wMG5VVmR4RnMKgEmxdd6rTnftyVlMMSNrsV/plRE+ppGa
            teMESrrgWge/IBO0TM+VvzWC3Xf7y79FiNXVynKKtVAjwfLBcvmF2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-17T18:07:01Z"
    mac: ENC[AES256_GCM,data:2tUMYeutJh0MuxqtzKEBgmWJNozOJodhwfb6OGV4eauL9mOXseHj9SpKUSWkPRiJNDcp20OlPVi/njOqSeVOvUZvujkX7zRhYhA2vHfbUevgGZwSN56rFgz6EwOOoDqZL4zt0CBcRoNiMafB2OsUWvX5PW1bvyFT76nX/ncnNOA=,iv:X1H2TO1vZZcveZKNSYdTjuL+qQZBr0pPKtud+4s748I=,tag:AcRKpCrAdQ32cYmp8NmIqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
