# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elastic-resources
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: elastic-operator
  path: ./kubernetes/apps/monitoring/elasticsearch/operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: cluster
  healthChecks:
    - apiVersion: kibana.k8s.elastic.co/v1
      kind: Kibana
      name: main
      namespace: search

  interval: 30m
  retryInterval: 1m
  timeout: 3m
