apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-secret
    namespace: monitoring
    labels:
        app.kubernetes.io/name: alertmanager-discord
type: Opaque
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:6ChlfMTUWYeZcLs46xgLSENkXmH/SdDPhzm0kYluuOlym79Z6urgr8IffU/qaL54ijjij2ldcbHriKd6vRL49TAJ5lPkTTgdalIgzJfYhR1fHTgkjbNdk+LRq1p1fjgZlwcqqFkAc804+2N3nYC8IxXqt7ZiLFS7Ng==,iv:FNgA3+IJyIno+lkEfDoSsfpcBfcNam6iMReneOrCtKQ=,tag:b1HNwZe3en4LJc8lfgkDGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17amptm4y84v3jwvz6af8z70k2dx5cq5p7sle38yj4zl7u2xlggeqypq72g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcldHZnltVUplKzZ4aEFo
            cWUxZmh2azRyV2ZObS9BcTAraHNkSFBpZVg0ClFHazI4MHNNRi9NSTB3eFozMGJT
            L3phaGlDbWhjNWZkYVVPOWk2K2RtQ0EKLS0tIEtBN0hRS05ZUHF2V1hSdHlqVnpH
            Y1NSbXZ6YmhYNVdHemRiSG9oRWFjMDQKldWqIbXU9PWBCPqDfBdQHfS0jCZkDpQ8
            sC0asbK53Yj+TbMFSofSSjYZT03LBcqs359Ea3cmAwIcy7v0DhUNig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T16:45:13Z"
    mac: ENC[AES256_GCM,data:cCSedRfQ2Sqy2Kv9GG2OBSDGHr4r9twPgXsFPJwPdU0UmBjyJwHrSK2V9wAZIK2muqpIoFguLnrIs5OY2iPtsvwAf/QD96bMLkv+njQHnTTrpbTNB8FPJ+UrhaA+Lnm/zColjFE6Wi4sJI8vAhBrNbiPOb6A2EC9lTlG8LcARQ8=,iv:go0P21Ll77kp0x7Gb8OlWqTcY9QBVLXr/PqXkdnY0uI=,tag:mwQAv8zVovavTkPB9RYDeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
