---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "emu.sh-production"
  namespace: networking
spec:
  secretName: "emu.sh-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "emu.sh"
  dnsNames:
    - "emu.sh"
    - "*.emu.sh"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "emu.sh-staging"
  namespace: networking
spec:
  secretName: "emu.sh-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "emu.sh"
  dnsNames:
    - "emu.sh"
    - "*.emu.sh"
