---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters/delta/flux/namespaces
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
