---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env: 
      PAPERLESS_OCR_LANGUAGES: por
      PAPERLESS_OCR_LANGUAGE: por
      PAPERLESS_TIME_ZONE: Europe/Lisbon
      PAPERLESS_REDIS: redis://paperless-redis-master:6379
      PAPERLESS_ADMIN_USER: ${SECRET_PAPERLESS_USERNAME}
      PAPERLESS_ADMIN_PASSWORD: ${SECRET_PAPERLESS_PASSWORD}
    data:
      enabled: true
      storageClass: local-path
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      media:
        enabled: true
        storageClass: local-path
        size: 10Gi
        accessModes:
          - ReadWriteOnce
    postgresql:
      enabled: true
    redis:
      enabled: true
      volumePermissions:
        enable: true
      replica:
        persistence:
          enabled: true
          size: 8Gi
          accessModes:
            - ReadWriteOnce
      master:
        persistence:
          enabled: true
          size: 8Gi
          accessModes:
            - ReadWriteOnce
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: "true"
          external-dns.alpha.kubernetes.io/hostname: paperless.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
            secretName: "paperless-tls"
