# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:2FqtW/VDReYu2j3/cJiwtvAdJ1XMSBUgI7BasQ==,iv:QQeJVrCHP1BuLfFQSFw9Oa5PQQWMW9YbobzZuItgSWo=,tag:ieH7RwX35Rfa8Ttnmf5g7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTXdsdXVCc1lQMjdoT1kz
            bGkrZmNNRVQ5aUJObkd2VTYrZGtZOHFaazFVCkhQY3RaaFE5dm1HZnRqRkJMV1JZ
            aEd3ZkJ6bkdXZUQvYjhjcXIwT2JMbkEKLS0tIE9QMjZTLy8yYkhtMEp2YlpOT3V1
            a3NDNEZvS3luSnJzd2dkYlh2a2xSdmcKQGUGQvuQx6V2zQY+EkOTxVgX5qiNtxmm
            +OQjwYBnfW5b5EoKMndt/Lf2o0v2DBKUs3e8tkFkSDoQhl2j/yu4kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T17:14:48Z"
    mac: ENC[AES256_GCM,data:N5gdvQVtNsluMOJiGynlS84uz6LwB0c6Rv9lpvL9by4NtivsRvzHqDFkuMOOBUJ+0OdwfPU6/bN9+4Li2vq5fX+GFgOx/6Mlw4Igw5CSv91P3ykbTX2ZYaF1tR8Yr1ExLYAYMAqJNLagSQsnnvVV/86DgTwNezgUBXvjpxxr/jo=,iv:Jm7Ajdxo93cLahuni9G9DhtNZ5airPg9dvu9DyF70Cc=,tag:l3MRKTZnV5FWJetAfhJIHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
