---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.9.1549
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
    securityContext:
      runAsUser: 1000

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-pvc
      media:
        enabled: true
        type: hostPath
        hostPath: /tmp/rclone
        mountPath: /mnt/drive
      downloads:
        enabled: true
        existingClaim: dlcache-pvc
        mountPath: /downloads

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        memory: "2048Mi"

    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: false
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.1.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
