apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: firefly
  name: "firefly-cron"
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 5
      template:
        metadata:
          labels:
            app: firefly
            tier: cron
        spec:
          containers:
            - name: cron
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - wget
              args:
                - "firefly:8080/api/v1/cron/$(STATIC_CRON_TOKEN)"
              env:
                - name: STATIC_CRON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: firefly-secrets
                      key: static_cron_token
          restartPolicy: Never
