authentik_domain: id.emu.sh
endpoints:
  - name: opnsense
    namespace: networking
    ip: 172.16.0.1
    ports:
      - name: opnsense
        port: 8443
        ingress: HTTPS
        protocol: TCP
        targetPort: 8443
        authentik: true
        hostname: opnsense.emu.sh
      - name: opnsense-ssh
        port: 22
        protocol: TCP
        targetPort: 22
    annotations:
  - name: alice
    namespace: networking
    ip: 172.16.0.2
    ports:
      - name: bitwarden
        port: 80
        protocol: TCP
        targetPort: 80
        ingress: HTTP
        authentik: false
        hostname: bw.emu.sh
      - name: invoke
        port: 7861
        protocol: TCP
        targetPort: 7861
        hostname: invoke.emu.sh
  - name: proxmox
    namespace: networking
    ip: 172.16.0.222
    ports:
      - name: proxmox
        port: 8006
        protocol: TCP
        targetPort: 8006
        ingress: HTTPS
        authentik: true
        hostname: proxmox.emu.sh
      - name: proxmox-ssh
        port: 22
        protocol: TCP
        targetPort: 22
    annotations:
  - name: ha
    namespace: networking
    ip: 172.16.0.4
    ports:
      - name: ha
        port: 8123
        protocol: TCP
        targetPort: 8123
        ingress: HTTP
        hostname: ha.emu.sh
  - name: htpc-download-box
    namespace: networking
    ip: 172.16.1.3
    ports:
      - name: Radarr
        port: 7878
        protocol: TCP
        targetPort: 7878
        ingress: HTTP
        authentik: true
        hostname: radarr.emu.sh
      - name: Sonarr
        port: 8989
        protocol: TCP
        targetPort: 8989
        ingress: HTTP
        authentik: true
        hostname: sonarr.emu.sh
      - name: Prowlarr
        port: 9696
        protocol: TCP
        targetPort: 9696
        ingress: HTTP
        authentik: true
        hostname: prowlarr.emu.sh
      - name: Lidarr
        port: 8686
        protocol: TCP
        targetPort: 8686
        ingress: HTTP
        authentik: true
        hostname: lidarr.emu.sh
      - name: qBittorrent
        port: 8080
        protocol: TCP
        targetPort: 8080
        ingress: HTTP
        authentik: true
        hostname: qbittorrent.emu.sh
