---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: bfdprofile
  namespace: networking
spec:
  receiveInterval: 380
  transmitInterval: 270
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: metallb-bgp
  namespace: networking
spec:
  myASN: 64500
  peerASN: 64501
  holdTime: 1m30s
  peerAddress: 172.16.0.1
  # https://github.com/metallb/metallb/issues/1537
  ebgpMultiHop: false
---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: networking
spec:
  addresses:
    - 10.96.69.0/24
  avoidBuggyIPs: true
# ---
# apiVersion: metallb.io/v1beta2
# kind: IPAddressPool
# metadata:
#   name: smtp-gateway
#   namespace: networking
# spec:
#   addresses:
#     - 192.168.10.11/32
# ---
# apiVersion: metallb.io/v1beta2
# kind: IPAddressPool
# metadata:
#   name: mailserv
#   namespace: networking
# spec:
#   addresses:
#     - 185.218.193.51/32
#     - 2001:67c:1104:fc00::587/128
---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: mosquitto
  namespace: networking
spec:
  addresses:
    - 192.168.10.10/32
---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: nginx
  namespace: networking
spec:
  addresses:
    - 192.168.10.80/32
---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: game-prefix-pool
  namespace: networking
spec:
  addresses:
    - 192.168.10.13/32
---
apiVersion: metallb.io/v1beta2
kind: IPAddressPool
metadata:
  name: public
  namespace: networking
spec:
  addresses:
    - 2001:67c:1104:fc00::100-2001:67c:1104:fc00::200
---
apiVersion: metallb.io/v1beta2
kind: BGPAdvertisement
metadata:
  name: bgp-lb
  namespace: networking
spec:
  ipAddressPools:
    - nginx
---
apiVersion: metallb.io/v1beta2
kind: BGPAdvertisement
metadata:
  name: bgp-other
  namespace: networking
spec:
  ipAddressPools:
    - default-pool
    # - smtp-gateway
    # - mailserv
    - public
    - game-prefix-pool
