---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  install:
    crds: CreateReplace

  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 5m
  values:
    controller:
      logLevel: debug
    prometheus:
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    speaker:
      enabled: false
    crds:
      enabled: true
      # https://github.com/cilium/cilium/issues/20436
      # https://github.com/metallb/metallb/issues/1512
      # This is really yank, when I have this many prefixes in use..
