apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: networking
spec:
  dnsNames:
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: wildcard-certificate-tls
