---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  targetNamespace: databases
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.2.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: postgres
    auth:
      existingSecret: postgresql
      secretKeys:
        postgresPassword: PG_PASSWORD
        adminPasswordKey: PG_PASSWORD
        replicationPasswordKey: PG_PASSWORD

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 15s
        scrapeTimeout: 10s
        selector:
          prometheus: prometheus
        additionalLabels:
          release: postgresql
