---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: databases
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  targetNamespace: databases
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: postgres
