{{- range .Values.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  ports:
  {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
  {{- end }}
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
    {{- range .ports }}
      - name: {{ .name }}
        port: {{ .port }}
        protocol: {{ .protocol }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    {{- if .sslHost }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    {{- end }}
    {{- if .auth }}
    nginx.ingress.kubernetes.io/auth-url: {{ .authentik_domain }}/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
    {{- end}}
spec:
  ingressClassName: {{ .ingressClassName }}
  rules:
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .ingressPort }}
        {{- if .auth }}
          - path: /outpost.goauthentik.io
              pathType: Prefix
              backend:
                  service:
                      name: authentik
                      port:
                          number: 80
      {{- end }}
{{- end }}
