{{- range $key, $value := .Values.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name | lower }}
  namespace: {{ $value.namespace }}
spec:
  ports:
  {{- range .ports }}
    - name: {{ .name | lower }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name | lower }}
  namespace: {{ .namespace }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
    {{- range .ports }}
      - name: {{ .name | lower }}
        port: {{ .port }}
        protocol: {{ .protocol }}
    {{- end }}
{{- range $p := .ports }}
{{- if .ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $p.name | lower }}
  namespace: {{ .namespace }}
  annotations:
    {{- if eq .ingress "HTTPS" }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    {{- end }}
    {{- if or (.authentik)  ($p.authentik) }}
    nginx.ingress.kubernetes.io/auth-url: https://id.emu.sh/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-response-headers: |-
      Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
    {{- end}}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - '*.emu.sh'
      secretName: emu.sh-production-tls
  rules:
    - host: {{ $p.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $value.name | lower }}
                port:
                  number: {{ $p.port }}
        {{- if or (.authentik)  ($p.authentik) }}
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
                service:
                    name: authentik
                    port:
                        number: 80
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
