---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-config
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "tempo"

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
