---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-tempo
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/Denver"
      ESPHOME_DASHBOARD_USE_PING: true
    tempo:

  traces:
    jaeger:
      grpc: true
      thriftBinary: false
      thriftCompact: true
      thriftHttp: true
    otlp:
      http: true
      grpc: true
    opencensus: true
    zipkin: true
  ## Tempo search parameters
  ##
  search:
    ## @param tempo.search.enabled Enable Tempo search
    ##
    enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: video-input-antenna
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: tempo-config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
