---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config
  namespace: monitoring
  annotations:
    nfs.io/storage-path: "influxdb"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "nfs-client"
