# cronjob.yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: networking
  name: dyndns-updater
spec:
  schedule: "0 */6 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: dyndns-updater
              image: curlimages/curl:7.75.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: dyndns-credentials
              command:
                - "/bin/sh"
                - "/app/dyndns-updater.sh"
              volumeMounts:
                - name: dyndns-updater
                  mountPath: /app/dyndns-updater.sh
                  subPath: dyndns-updater.sh
                  readOnly: true
            - name: cname-updater
              image: curlimages/curl:7.75.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: cname-credentials
              command:
                - "/bin/sh"
                - "/app/cname-updater.sh"
              volumeMounts:
                - name: cname-updater
                  mountPath: /app/cname-updater.sh
                  subPath: cname-updater.sh
                  readOnly: true
          volumes:
            - name: dyndns-updater
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: dyndns-updater
                      items:
                        - key: dyndns-updater.sh
                          path: dyndns-updater.sh
            - name: cname-updater
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: cname-updater
                      items:
                        - key: cname-updater.sh
                          path: cname-updater.sh
