---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/rafaribe/home-ops
  ignore: |
    # exclude all
    /*
    # include charts dirs
    !/kubernetes/charts
    # include gitops dirs
    !/kubernetes/global
    !/kubernetes/clusters/delta
    !/kubernetes/manifests
    # exclude files from gitops dirs
    /kubernetes/**/*.md
    /kubernetes/**/*.tmpl
