---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: networking
spec:
  ports:
    - name: proxmox
      port: 8006
      protocol: TCP
      targetPort: 8006
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: networking
subsets:
  - addresses:
      - ip: 172.16.0.222
    ports:
      - name: nfs-tcp
        port: 2049
        protocol: TCP
      - name: nfs-tcp2
        port: 111
        protocol: TCP
        protocol: TCP
      - name: proxmox
        port: 8006
        protocol: TCP
