# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kubesec

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/kube-linter.yaml"
      - ".github/linters/kubelinter.yaml"
      - "kubernetes/clusters/**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
    paths:
      - ".github/workflows/kube-linter.yaml"
      - ".github/linters/kubelinter.yaml"
      - "kubernetes/clusters/**"
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    name: Kubelinter
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: kubernetes/clusters
          config: .github/linters/kubelinter.yaml
          format: sarif
          output-file: kube-linter.sarif